.TH "Tetris::Tests::BlockTest" 3 "MultiTetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tetris::Tests::BlockTest
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:testing::Test\&.
.SS "Защищенные данные"

.in +1c
.ti -1c
.RI "\fBModel::Blocks::BlocksFactory\fP \fB_factory\fP"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для MultiTetris из исходного текста\&.
