.TH "Tetris::View::Qt::QtApplicaion" 3 "MultiTetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tetris::View::Qt::QtApplicaion \- Класс, реализующий интерфейс \fBIApplication\fP для графического приложения на базе Qt\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <QtApplication\&.h>\fP
.PP
Базовые классы:\fBTetris::View::IApplication\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBQtApplicaion\fP (AbstractModelPtr model, unsigned int countWidgets)"
.br
.RI "Конструктор класса\&. "
.ti -1c
.RI "\fB~QtApplicaion\fP ()"
.br
.RI "Деструктор класса\&. Освобождает ресурсы, связанные с приложением\&. "
.ti -1c
.RI "bool \fBisExecution\fP () const override"
.br
.RI "Метод для проверки состояния выполнения приложения\&. "
.in -1c

Открытые члены унаследованные от \fBTetris::View::IApplication\fP
.in +1c
.ti -1c
.RI "virtual \fB~IApplication\fP ()=default"
.br
.RI "Дефолтный деструктор "
.in -1c
.SH "Подробное описание"
.PP 
Класс, реализующий интерфейс \fBIApplication\fP для графического приложения на базе Qt\&. 
.SH "Конструктор(ы)"
.PP 
.SS "Tetris::View::Qt::QtApplicaion::QtApplicaion (AbstractModelPtr model, unsigned int countWidgets)"

.PP
Конструктор класса\&. 
.PP
\fBАргументы\fP
.RS 4
\fImodel\fP Указатель на модель, используемую приложением\&. 
.br
\fIcountWidgets\fP Количество виджетов, создаваемых приложением\&. 
.RE
.PP

.SH "Методы"
.PP 
.SS "bool Tetris::View::Qt::QtApplicaion::isExecution () const\fR [override]\fP, \fR [virtual]\fP"

.PP
Метод для проверки состояния выполнения приложения\&. 
.PP
\fBВозвращает\fP
.RS 4
true, если приложение выполняется; false в противном случае\&. 
.br
 
.RE
.PP

.PP
Замещает \fBTetris::View::IApplication\fP\&.

.SH "Автор"
.PP 
Автоматически создано Doxygen для MultiTetris из исходного текста\&.
