.TH "Tetris::View::SFML::Map" 3 "project(MultiTetris LANGUAGES CXX)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tetris::View::SFML::Map
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:sf::Drawable и sf::Transformable\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBMap\fP (sf::Vector2f windowSize, bool withBorder=false)"
.br
.RI "Конструктор класса \fBMap\fP\&. "
.ti -1c
.RI "void \fBSetMap\fP (const std::vector< Model::TypeColor > &map, \fBModel::MapSize\fP size)"
.br
.RI "Установить карту "
.in -1c
.SH "Конструктор(ы)"
.PP 
.SS "Tetris::View::SFML::Map::Map (sf::Vector2f windowSize, bool withBorder = \fRfalse\fP)"

.PP
Конструктор класса \fBMap\fP\&. 
.PP
\fBАргументы\fP
.RS 4
\fIwindowSize\fP Размер окна отображения 
.br
\fIwithBorder\fP Указывает, нужно ли отображать границы 
.RE
.PP

.SH "Методы"
.PP 
.SS "void Tetris::View::SFML::Map::SetMap (const std::vector< Model::TypeColor > & map, \fBModel::MapSize\fP size)"

.PP
Установить карту 
.PP
\fBАргументы\fP
.RS 4
\fImap\fP Вектор с цветами блоков 
.br
\fIsize\fP Размер карты (строки и столбцы) 
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для project(MultiTetris LANGUAGES CXX) из исходного текста\&.
