.TH "Tetris::View::Qt::PreviewBlock" 3 "MultiTetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tetris::View::Qt::PreviewBlock \- Класс \fBPreviewBlock\fP представляет собой блок предварительного просмотра в игре Тетрис\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <PreviewBlock\&.h>\fP
.PP
Базовые классы:\fBTetris::View::Qt::Map\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBPreviewBlock\fP (QWindow *parent=nullptr, bool withBorder=false)"
.br
.RI "Конструктор класса \fBPreviewBlock\fP\&. "
.ti -1c
.RI "void \fBSetBlock\fP (const AbstractBlockPtr block)"
.br
.RI "Устанавливает блок для предварительного просмотра\&. "
.ti -1c
.RI "Model::TypeBlock \fBGetType\fP () const"
.br
.RI "Возвращает тип блока\&. "
.in -1c

Открытые члены унаследованные от \fBTetris::View::Qt::Map\fP
.in +1c
.ti -1c
.RI "\fBMap\fP (QWindow *parent, bool withBorder=false)"
.br
.RI "Конструктор класса \fBMap\fP\&. "
.ti -1c
.RI "void \fBSetMap\fP (const std::vector< Model::TypeColor > &map, \fBModel::MapSize\fP size)"
.br
.RI "Установить карту "
.in -1c
.SS "Дополнительные унаследованные члены"


Защищенные члены унаследованные от \fBTetris::View::Qt::Map\fP
.in +1c
.ti -1c
.RI "bool \fBevent\fP (QEvent *event) override"
.br
.RI "Обработка событий "
.ti -1c
.RI "void \fBresizeEvent\fP (QResizeEvent *\fBevent\fP) override"
.br
.RI "Обработка изменения размера окна "
.ti -1c
.RI "void \fBexposeEvent\fP (QExposeEvent *\fBevent\fP) override"
.br
.RI "Обработка события отображения окна "
.in -1c
.SH "Подробное описание"
.PP 
Класс \fBPreviewBlock\fP представляет собой блок предварительного просмотра в игре Тетрис\&. 
.SH "Конструктор(ы)"
.PP 
.SS "Tetris::View::Qt::PreviewBlock::PreviewBlock (QWindow * parent = \fRnullptr\fP, bool withBorder = \fRfalse\fP)"

.PP
Конструктор класса \fBPreviewBlock\fP\&. 
.PP
\fBАргументы\fP
.RS 4
\fIparent\fP - родительское окно, по умолчанию nullptr\&. 
.br
\fIwithBorder\fP - флаг, указывающий, нужно ли отображать границу блока\&. 
.RE
.PP

.SH "Методы"
.PP 
.SS "void Tetris::View::Qt::PreviewBlock::SetBlock (const AbstractBlockPtr block)"

.PP
Устанавливает блок для предварительного просмотра\&. 
.PP
\fBАргументы\fP
.RS 4
\fIblock\fP - указатель на блок, который нужно установить\&. 
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для MultiTetris из исходного текста\&.
