.TH "Tetris::View::SFML::Text" 3 "project(MultiTetris LANGUAGES CXX)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tetris::View::SFML::Text \- Класс \fBText\fP представляет собой текстовое поле в игре Тетрис\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Text\&.h>\fP
.PP
Базовые классы:sf::Text\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBText\fP (const std::string &fontPath, sf::Color colorText, std::uint32_t style)"
.br
.RI "Конструктор класса \fBText\fP\&. "
.in -1c
.SH "Подробное описание"
.PP 
Класс \fBText\fP представляет собой текстовое поле в игре Тетрис\&. 

Этот класс наследуется от sf::Text и добавляет дополнительные возможности для работы с текстом\&. 
.SH "Конструктор(ы)"
.PP 
.SS "Tetris::View::SFML::Text::Text (const std::string & fontPath, sf::Color colorText, std::uint32_t style)"

.PP
Конструктор класса \fBText\fP\&. 
.PP
\fBАргументы\fP
.RS 4
\fIfontPath\fP Путь к файлу шрифта\&. 
.br
\fIcolorText\fP Цвет текста\&. 
.br
\fIstyle\fP Стиль текста\&. 
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для project(MultiTetris LANGUAGES CXX) из исходного текста\&.
