.TH "Tetris::Model::Map" 3 "MultiTetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tetris::Model::Map \- Класс реализации карты для игры Тетрис  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Map\&.h>\fP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBMap\fP (size_t columns=10, size_t rows=25)"
.br
.RI "Конструктор по умолчанию, инициализирует пустую карту "
.ti -1c
.RI "std::vector< TypeColor > \fBGetMap\fP ()"
.br
.RI "Получить текущую карту "
.ti -1c
.RI "\fBMapSize\fP \fBGetSize\fP () const"
.br
.RI "Получить размер карты "
.ti -1c
.RI "bool \fBIsFullMap\fP ()"
.br
.RI "Проверить, заполнена ли карта "
.ti -1c
.RI "void \fBRestart\fP ()"
.br
.RI "Перезапустить карту, очищая её "
.ti -1c
.RI "void \fBSetBlock\fP (AbstractBlockPtr block)"
.br
.RI "Установить активный блок на карту "
.ti -1c
.RI "bool \fBHasActiveBlock\fP () const"
.br
.RI "Проверить, имеется ли активный блок "
.ti -1c
.RI "void \fBMoveBlock\fP (Command cmn)"
.br
.RI "Переместить активный блок на карте "
.ti -1c
.RI "unsigned int \fBGetCountDeletedLines\fP () const"
.br
.RI "Получить количество удаленных линий "
.in -1c
.SH "Подробное описание"
.PP 
Класс реализации карты для игры Тетрис 
.SH "Конструктор(ы)"
.PP 
.SS "Tetris::Model::Map::Map (size_t columns = \fR10\fP, size_t rows = \fR25\fP)"

.PP
Конструктор по умолчанию, инициализирует пустую карту 
.PP
\fBАргументы\fP
.RS 4
\fIcolumns\fP Количество столбцов карты 
.br
\fIrows\fP Количество строк карты 
.RE
.PP

.SH "Методы"
.PP 
.SS "unsigned int Tetris::Model::Map::GetCountDeletedLines () const"

.PP
Получить количество удаленных линий 
.PP
\fBВозвращает\fP
.RS 4
Количество удаленных линий 
.RE
.PP

.SS "std::vector< TypeColor > Tetris::Model::Map::GetMap ()"

.PP
Получить текущую карту 
.PP
\fBВозвращает\fP
.RS 4
Текущая карта 
.RE
.PP

.SS "\fBMapSize\fP Tetris::Model::Map::GetSize () const"

.PP
Получить размер карты 
.PP
\fBВозвращает\fP
.RS 4
Размер карты в виде \fBMapSize\fP 
.RE
.PP

.SS "bool Tetris::Model::Map::HasActiveBlock () const"

.PP
Проверить, имеется ли активный блок 
.PP
\fBВозвращает\fP
.RS 4
True, если активный блок присутствует, иначе false 
.RE
.PP

.SS "bool Tetris::Model::Map::IsFullMap ()"

.PP
Проверить, заполнена ли карта 
.PP
\fBВозвращает\fP
.RS 4
True, если карта заполнена, иначе false 
.RE
.PP

.SS "void Tetris::Model::Map::MoveBlock (Command cmn)"

.PP
Переместить активный блок на карте 
.PP
\fBАргументы\fP
.RS 4
\fIcmn\fP Команда для перемещения 
.RE
.PP

.SS "void Tetris::Model::Map::SetBlock (AbstractBlockPtr block)"

.PP
Установить активный блок на карту 
.PP
\fBАргументы\fP
.RS 4
\fIblock\fP Указатель на блок 
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для MultiTetris из исходного текста\&.
