.TH "Tetris::Model::DescriptionModel" 3 "project(MultiTetris LANGUAGES CXX)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tetris::Model::DescriptionModel \- Описание модели игры  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DescriptionModel\&.h>\fP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "std::vector< TypeColor > \fBmap\fP"
.br
.RI "Игровая карта "
.ti -1c
.RI "\fBMapSize\fP \fBsize\fP"
.br
.RI "Размер карты "
.ti -1c
.RI "AbstractBlockPtr \fBnextBlock\fP {\fBnullptr\fP}"
.br
.RI "Следующий блок "
.ti -1c
.RI "std::optional< \fBunsigned\fP \fBint\fP > \fBscore\fP"
.br
.RI "Текущий счет "
.in -1c
.SH "Подробное описание"
.PP 
Описание модели игры 

.SH "Автор"
.PP 
Автоматически создано Doxygen для project(MultiTetris LANGUAGES CXX) из исходного текста\&.
