.TH "Tetris::Controller::MoveController" 3 "project(MultiTetris LANGUAGES CXX)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tetris::Controller::MoveController
.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBMoveController\fP (AbstractModelPtr model)"
.br
.ti -1c
.RI "void \fBMove\fP (Model::Command cmn)"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для project(MultiTetris LANGUAGES CXX) из исходного текста\&.
