.TH "Tetris::Model::MapSize" 3 "project(MultiTetris LANGUAGES CXX)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tetris::Model::MapSize \- Размер карты  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Types\&.h>\fP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "size_t \fBcolumns\fP"
.br
.RI "Количество колонок "
.ti -1c
.RI "size_t \fBrows\fP"
.br
.RI "Количество строк "
.in -1c
.SH "Подробное описание"
.PP 
Размер карты 

.SH "Автор"
.PP 
Автоматически создано Doxygen для project(MultiTetris LANGUAGES CXX) из исходного текста\&.
