.TH "Tetris::Controller::TimeController" 3 "project(MultiTetris LANGUAGES CXX)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tetris::Controller::TimeController
.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBTimeController\fP (AbstractModelPtr model, std::chrono::seconds interval)"
.br
.ti -1c
.RI "void \fBCheckTimer\fP ()"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для project(MultiTetris LANGUAGES CXX) из исходного текста\&.
