.TH "Tetris::Model::Blocks::Creator< C, Base >" 3 "project(MultiTetris LANGUAGES CXX)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tetris::Model::Blocks::Creator< C, Base > \- Реализация создателя для конкретного типа объекта\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <AbstractCreator\&.h>\fP
.PP
Базовые классы:\fBTetris::Model::Blocks::AbstractCreator< Base >\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBCreator\fP ()"
.br
.RI "Конструктор по умолчанию\&. "
.ti -1c
.RI "virtual \fB~Creator\fP ()"
.br
.RI "Виртуальный деструктор\&. "
.ti -1c
.RI "Base * \fBCreate\fP (TypeColor color) const override"
.br
.RI "Создать объект с заданным цветом\&. "
.in -1c

Открытые члены унаследованные от \fBTetris::Model::Blocks::AbstractCreator< Base >\fP
.in +1c
.ti -1c
.RI "\fBAbstractCreator\fP ()"
.br
.RI "Конструктор по умолчанию\&. "
.ti -1c
.RI "virtual \fB~AbstractCreator\fP ()"
.br
.RI "Виртуальный деструктор\&. "
.in -1c
.SH "Подробное описание"
.PP 

.SS "template<class C, class Base>
.br
class Tetris::Model::Blocks::Creator< C, Base >"Реализация создателя для конкретного типа объекта\&. 


.PP
\fBПараметры шаблона\fP
.RS 4
\fIC\fP Тип создаваемого объекта\&. 
.br
\fIBase\fP Базовый класс создаваемых объектов\&. 
.RE
.PP

.SH "Методы"
.PP 
.SS "template<class C , class Base > Base * \fBTetris::Model::Blocks::Creator\fP< C, Base >::Create (TypeColor color) const\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
Создать объект с заданным цветом\&. 
.PP
\fBАргументы\fP
.RS 4
\fIcolor\fP Цвет создаваемого объекта\&. 
.RE
.PP
\fBВозвращает\fP
.RS 4
Указатель на созданный объект\&. 
.RE
.PP

.PP
Замещает \fBTetris::Model::Blocks::AbstractCreator< Base >\fP\&.

.SH "Автор"
.PP 
Автоматически создано Doxygen для project(MultiTetris LANGUAGES CXX) из исходного текста\&.
