.TH "Tetris::View::IApplication" 3 "project(MultiTetris LANGUAGES CXX)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tetris::View::IApplication
.SH SYNOPSIS
.br
.PP
.PP
Производные классы:\fBTetris::View::Qt::QtApplicaion\fP и \fBTetris::View::SFML::SFMLApplication\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "virtual void \fBRun\fP ()=0"
.br
.ti -1c
.RI "virtual bool \fBisExecution\fP () const =0"
.br
.in -1c
.SH "Методы"
.PP 
.SS "virtual bool Tetris::View::IApplication::isExecution () const\fR [pure virtual]\fP"

.PP
Замещается в \fBTetris::View::Qt::QtApplicaion\fP и \fBTetris::View::SFML::SFMLApplication\fP\&.
.SS "virtual void Tetris::View::IApplication::Run ()\fR [pure virtual]\fP"

.PP
Замещается в \fBTetris::View::Qt::QtApplicaion\fP и \fBTetris::View::SFML::SFMLApplication\fP\&.

.SH "Автор"
.PP 
Автоматически создано Doxygen для project(MultiTetris LANGUAGES CXX) из исходного текста\&.
