.TH "Tetris::View::Qt::Map" 3 "project(MultiTetris LANGUAGES CXX)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tetris::View::Qt::Map
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:QWindow\&.
.PP
Производные классы:\fBTetris::View::Qt::PreviewBlock\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBMap\fP (QWindow *parent, bool withBorder=false)"
.br
.RI "Конструктор класса \fBMap\fP\&. "
.ti -1c
.RI "void \fBSetMap\fP (const std::vector< Model::TypeColor > &map, \fBModel::MapSize\fP size)"
.br
.RI "Установить карту "
.in -1c
.SS "Защищенные члены"

.in +1c
.ti -1c
.RI "bool \fBevent\fP (QEvent *event) override"
.br
.RI "Обработка событий "
.ti -1c
.RI "void \fBresizeEvent\fP (QResizeEvent *\fBevent\fP) override"
.br
.RI "Обработка изменения размера окна "
.ti -1c
.RI "void \fBexposeEvent\fP (QExposeEvent *\fBevent\fP) override"
.br
.RI "Обработка события отображения окна "
.in -1c
.SH "Конструктор(ы)"
.PP 
.SS "Tetris::View::Qt::Map::Map (QWindow * parent, bool withBorder = \fRfalse\fP)"

.PP
Конструктор класса \fBMap\fP\&. 
.PP
\fBАргументы\fP
.RS 4
\fIparent\fP Указатель на родительское окно 
.br
\fIwithBorder\fP Флаг, указывающий, нужно ли отображать рамку 
.RE
.PP

.SH "Методы"
.PP 
.SS "bool Tetris::View::Qt::Map::event (QEvent * event)\fR [override]\fP, \fR [protected]\fP"

.PP
Обработка событий 
.PP
\fBАргументы\fP
.RS 4
\fIevent\fP Указатель на событие 
.RE
.PP
\fBВозвращает\fP
.RS 4
true, если событие обработано 
.RE
.PP

.SS "void Tetris::View::Qt::Map::exposeEvent (QExposeEvent * event)\fR [override]\fP, \fR [protected]\fP"

.PP
Обработка события отображения окна 
.PP
\fBАргументы\fP
.RS 4
\fIevent\fP Указатель на событие отображения 
.RE
.PP

.SS "void Tetris::View::Qt::Map::resizeEvent (QResizeEvent * event)\fR [override]\fP, \fR [protected]\fP"

.PP
Обработка изменения размера окна 
.PP
\fBАргументы\fP
.RS 4
\fIevent\fP Указатель на событие изменения размера 
.RE
.PP

.SS "void Tetris::View::Qt::Map::SetMap (const std::vector< Model::TypeColor > & map, \fBModel::MapSize\fP size)"

.PP
Установить карту 
.PP
\fBАргументы\fP
.RS 4
\fImap\fP Вектор, представляющий карту с блоками 
.br
\fIsize\fP Размер карты (количество строк и столбцов) 
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для project(MultiTetris LANGUAGES CXX) из исходного текста\&.
