.TH "Tetris::Model::AbstractWidget" 3 "project(MultiTetris LANGUAGES CXX)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tetris::Model::AbstractWidget \- Интерфейс для виджетов в игре Тетрис  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <AbstractWidget\&.h>\fP
.PP
Производные классы:\fBTetris::View::Qt::QAdapterWidget\fP и \fBTetris::View::SFML::Widget\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "virtual \fB~AbstractWidget\fP ()=default"
.br
.RI "Деструктор по умолчанию "
.ti -1c
.RI "virtual void \fBUpdate\fP ()=0"
.br
.RI "Обновление состояния виджета "
.ti -1c
.RI "virtual bool \fBIsOpen\fP () const =0"
.br
.RI "Проверка, открыт ли виджет "
.ti -1c
.RI "virtual void \fBSlotCloseWidget\fP ()=0"
.br
.RI "Закрытие виджета "
.ti -1c
.RI "virtual void \fBSlotUpdateWidget\fP (DescriptionModelPtr descp)"
.br
.RI "Обновление виджета на основе описания модели "
.ti -1c
.RI "DescriptionModelPtr \fBGetDescriptionModel\fP ()"
.br
.RI "Обновление виджета на основе описания модели "
.in -1c
.SH "Подробное описание"
.PP 
Интерфейс для виджетов в игре Тетрис 
.SH "Методы"
.PP 
.SS "DescriptionModelPtr Tetris::Model::AbstractWidget::GetDescriptionModel ()\fR [inline]\fP"

.PP
Обновление виджета на основе описания модели 
.PP
\fBВозвращает\fP
.RS 4
descp Описание текущего состояния модели 
.RE
.PP

.SS "virtual bool Tetris::Model::AbstractWidget::IsOpen () const\fR [pure virtual]\fP"

.PP
Проверка, открыт ли виджет 
.PP
\fBВозвращает\fP
.RS 4
true, если виджет открыт; иначе false 
.RE
.PP

.PP
Замещается в \fBTetris::View::Qt::QAdapterWidget\fP и \fBTetris::View::SFML::Widget\fP\&.
.SS "virtual void Tetris::Model::AbstractWidget::SlotCloseWidget ()\fR [pure virtual]\fP"

.PP
Закрытие виджета 
.PP
Замещается в \fBTetris::View::Qt::QAdapterWidget\fP и \fBTetris::View::SFML::Widget\fP\&.
.SS "virtual void Tetris::Model::AbstractWidget::SlotUpdateWidget (DescriptionModelPtr descp)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Обновление виджета на основе описания модели 
.PP
\fBАргументы\fP
.RS 4
\fIdescp\fP Описание текущего состояния модели 
.RE
.PP

.PP
Переопределяется в \fBTetris::View::Qt::QAdapterWidget\fP\&.
.SS "virtual void Tetris::Model::AbstractWidget::Update ()\fR [pure virtual]\fP"

.PP
Обновление состояния виджета 
.PP
Замещается в \fBTetris::View::Qt::QAdapterWidget\fP и \fBTetris::View::SFML::Widget\fP\&.

.SH "Автор"
.PP 
Автоматически создано Doxygen для project(MultiTetris LANGUAGES CXX) из исходного текста\&.
