.TH "Tetris::Model::Blocks::BlocksFactory" 3 "MultiTetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tetris::Model::Blocks::BlocksFactory \- Фабрика для создания блоков в игре Тетрис\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <BlocksFactory\&.h>\fP
.PP
Базовые классы:\fBTetris::Model::Blocks::ObjectFactory< AbstractBlock, TypeBlock >\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBAbstractBlock\fP * \fBCreate\fP (TypeBlock id, TypeColor color)"
.br
.RI "Создать блок с заданным идентификатором и цветом\&. "
.ti -1c
.RI "int \fBSize\fP () const"
.br
.RI "Получить количество инициализированных блоков\&. "
.in -1c

Открытые члены унаследованные от \fBTetris::Model::Blocks::ObjectFactory< AbstractBlock, TypeBlock >\fP
.in +1c
.ti -1c
.RI "\fBObjectFactory\fP ()"
.br
.RI "Конструктор "
.ti -1c
.RI "virtual \fB~ObjectFactory\fP ()"
.br
.RI "Виртуальный деструктор "
.ti -1c
.RI "void \fBadd\fP (const TypeBlock &id)"
.br
.RI "Добавить новый тип объекта в фабрику\&. "
.in -1c
.SS "Дополнительные унаследованные члены"


Защищенные типы унаследованные от \fBTetris::Model::Blocks::ObjectFactory< AbstractBlock, TypeBlock >\fP
.in +1c
.ti -1c
.RI "using \fBAbstractFactory\fP"
.br
.RI "Базовый тип абстрактной фабрики для создания объектов\&. "
.ti -1c
.RI "using \fBFactoryMap\fP"
.br
.RI "Тип мапы, связывающей идентификаторы объектов с соответствующими фабриками\&. "
.in -1c

Защищенные члены унаследованные от \fBTetris::Model::Blocks::ObjectFactory< AbstractBlock, TypeBlock >\fP
.in +1c
.ti -1c
.RI "void \fBregisterClass\fP (const TypeBlock &id, \fBAbstractFactory\fP *p)"
.br
.RI "Зарегистрировать фабрику для создания объекта с заданным идентификатором\&. "
.in -1c

Защищенные данные унаследованные от \fBTetris::Model::Blocks::ObjectFactory< AbstractBlock, TypeBlock >\fP
.in +1c
.ti -1c
.RI "\fBFactoryMap\fP \fB_factory\fP"
.br
.RI "Мапа зарегистрированных объектов и их фабрик\&. "
.in -1c
.SH "Подробное описание"
.PP 
Фабрика для создания блоков в игре Тетрис\&. 
.SH "Методы"
.PP 
.SS "\fBAbstractBlock\fP * Tetris::Model::Blocks::BlocksFactory::Create (TypeBlock id, TypeColor color)\fR [inline]\fP"

.PP
Создать блок с заданным идентификатором и цветом\&. 
.PP
\fBАргументы\fP
.RS 4
\fIid\fP Идентификатор блока\&. 
.br
\fIcolor\fP Цвет блока\&. 
.RE
.PP
\fBВозвращает\fP
.RS 4
Указатель на созданный блок\&. 
.RE
.PP

.SS "int Tetris::Model::Blocks::BlocksFactory::Size () const\fR [inline]\fP"

.PP
Получить количество инициализированных блоков\&. 
.PP
\fBВозвращает\fP
.RS 4
Количество зарегистрированных блоков\&. 
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для MultiTetris из исходного текста\&.
