.TH "Tetris::Controller::TimeController" 3 "MultiTetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tetris::Controller::TimeController \- Контроллер движения фигур  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <TimeController\&.h>\fP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBTimeController\fP (AbstractModelPtr model, std::chrono::seconds interval)"
.br
.RI "Конструктор "
.ti -1c
.RI "void \fBCheckTimer\fP ()"
.br
.RI "Проверка проверка промежутка времени между испускания прошлого сигнала и interval\&. "
.in -1c
.SH "Подробное описание"
.PP 
Контроллер движения фигур 
.SH "Конструктор(ы)"
.PP 
.SS "Tetris::Controller::TimeController::TimeController (AbstractModelPtr model, std::chrono::seconds interval)"

.PP
Конструктор 
.PP
\fBАргументы\fP
.RS 4
\fImodel\fP Модель игры на которую воздействует контроллер 
.br
\fIinterval\fP Интервал времени перемещения блока 
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для MultiTetris из исходного текста\&.
