.TH "Tetris::Model::AbstractModel" 3 "project(MultiTetris LANGUAGES CXX)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tetris::Model::AbstractModel \- Абстрактный класс модели для управления игровыми данными  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <AbstractModel\&.h>\fP
.PP
Производные классы:\fBTetris::Model::ModelGame\fP\&.
.SS "Открытые типы"

.in +1c
.ti -1c
.RI "using \fBTypeSignalUpdateWidgets\fP = boost::signals2::signal<void(DescriptionModelPtr)>"
.br
.RI "Сигнал для обновления виджетов с описанием модели "
.ti -1c
.RI "using \fBTypeSignalCloseWidgets\fP = boost::signals2::signal<void()>"
.br
.RI "Сигнал для закрытия виджетов "
.in -1c
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBAbstractModel\fP ()"
.br
.RI "Конструктор "
.ti -1c
.RI "virtual \fB~AbstractModel\fP ()"
.br
.RI "Деструктор "
.ti -1c
.RI "void \fBSlotUpdate\fP (Command command)"
.br
.RI "Метод для обновления модели с полученной командой "
.ti -1c
.RI "void \fBSetWidget\fP (AbstractWidgetPtr view)"
.br
.RI "Установка виджета для обновления и закрытия "
.in -1c
.SS "Защищенные члены"

.in +1c
.ti -1c
.RI "virtual void \fBUpdateModel\fP (Command command, DescriptionModelPtr &desc)=0"
.br
.RI "Чисто виртуальный метод для обновления модели "
.in -1c
.SS "Защищенные данные"

.in +1c
.ti -1c
.RI "\fBTypeSignalUpdateWidgets\fP \fBSignalUpdateWidgets\fP"
.br
.RI "Сигнал для обновления виджетов "
.ti -1c
.RI "\fBTypeSignalCloseWidgets\fP \fBSignalCloseWidgets\fP"
.br
.RI "Сигнал для закрытия виджетов "
.in -1c
.SH "Подробное описание"
.PP 
Абстрактный класс модели для управления игровыми данными 
.SH "Методы"
.PP 
.SS "void Tetris::Model::AbstractModel::SetWidget (AbstractWidgetPtr view)\fR [inline]\fP"

.PP
Установка виджета для обновления и закрытия 
.PP
\fBАргументы\fP
.RS 4
\fIview\fP Указатель на виджет 
.RE
.PP

.SS "void Tetris::Model::AbstractModel::SlotUpdate (Command command)\fR [inline]\fP"

.PP
Метод для обновления модели с полученной командой 
.PP
\fBАргументы\fP
.RS 4
\fIcommand\fP Команда для обновления 
.RE
.PP

.SS "virtual void Tetris::Model::AbstractModel::UpdateModel (Command command, DescriptionModelPtr & desc)\fR [protected]\fP, \fR [pure virtual]\fP"

.PP
Чисто виртуальный метод для обновления модели 
.PP
\fBАргументы\fP
.RS 4
\fIcommand\fP Команда для обновления 
.br
\fIdesc\fP Ссылка на описание модели 
.RE
.PP

.PP
Замещается в \fBTetris::Model::ModelGame\fP\&.

.SH "Автор"
.PP 
Автоматически создано Doxygen для project(MultiTetris LANGUAGES CXX) из исходного текста\&.
