.TH "Tetris::Controller::MoveController" 3 "MultiTetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tetris::Controller::MoveController \- Контроллер движения фигур  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <MoveController\&.h>\fP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBMoveController\fP (AbstractModelPtr model)"
.br
.RI "Конструктор "
.ti -1c
.RI "void \fBMove\fP (Model::Command cmn)"
.br
.RI "Переместить фигуру "
.in -1c
.SH "Подробное описание"
.PP 
Контроллер движения фигур 
.SH "Конструктор(ы)"
.PP 
.SS "Tetris::Controller::MoveController::MoveController (AbstractModelPtr model)"

.PP
Конструктор 
.PP
\fBАргументы\fP
.RS 4
\fImodel\fP Модель игры на которую воздействует контроллер 
.RE
.PP

.SH "Методы"
.PP 
.SS "void Tetris::Controller::MoveController::Move (Model::Command cmn)"

.PP
Переместить фигуру 
.PP
\fBАргументы\fP
.RS 4
\fIcmn\fP Комманда 
.br
 
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для MultiTetris из исходного текста\&.
