.TH "Tetris::View::SFML::WidgetPreviewBlock" 3 "MultiTetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tetris::View::SFML::WidgetPreviewBlock \- Класс \fBWidgetPreviewBlock\fP отвечает за отображение предварительного просмотра блока в игре Тетрис\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <WidgetPreviewBlock\&.h>\fP
.PP
Базовые классы:sf::Drawable и sf::Transformable\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBWidgetPreviewBlock\fP (const sf::Vector2f &windowSize, bool withBorder=false)"
.br
.RI "Конструктор класса\&. "
.ti -1c
.RI "void \fBSetBlock\fP (const AbstractBlockPtr block)"
.br
.RI "Устанавливает блок для предварительного просмотра\&. "
.ti -1c
.RI "Model::TypeBlock \fBGetType\fP () const"
.br
.RI "Возвращает тип текущего блока\&. "
.in -1c
.SH "Подробное описание"
.PP 
Класс \fBWidgetPreviewBlock\fP отвечает за отображение предварительного просмотра блока в игре Тетрис\&. 
.SH "Конструктор(ы)"
.PP 
.SS "Tetris::View::SFML::WidgetPreviewBlock::WidgetPreviewBlock (const sf::Vector2f & windowSize, bool withBorder = \fRfalse\fP)"

.PP
Конструктор класса\&. 
.PP
\fBАргументы\fP
.RS 4
\fIwindowSize\fP Размер окна для отображения блока\&. 
.br
\fIwithBorder\fP Флаг, указывающий, нужно ли отображать границу\&. 
.RE
.PP

.SH "Методы"
.PP 
.SS "Model::TypeBlock Tetris::View::SFML::WidgetPreviewBlock::GetType () const"

.PP
Возвращает тип текущего блока\&. 
.PP
\fBВозвращает\fP
.RS 4
Тип блока\&. 
.RE
.PP

.SS "void Tetris::View::SFML::WidgetPreviewBlock::SetBlock (const AbstractBlockPtr block)"

.PP
Устанавливает блок для предварительного просмотра\&. 
.PP
\fBАргументы\fP
.RS 4
\fIblock\fP Указатель на блок, который нужно отобразить\&. 
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для MultiTetris из исходного текста\&.
