.TH "Tetris::View::SFML::SFMLApplication" 3 "MultiTetris" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tetris::View::SFML::SFMLApplication \- Класс, реализующий интерфейс \fBIApplication\fP для графического приложения на базе SFML\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SFMLApplication\&.h>\fP
.PP
Базовые классы:\fBTetris::View::IApplication\fP\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBSFMLApplication\fP (AbstractModelPtr model, unsigned int countWidgets, const std::string &fontPath)"
.br
.RI "Конструктор\&. "
.ti -1c
.RI "\fB~SFMLApplication\fP ()"
.br
.RI "Деструктор\&. "
.ti -1c
.RI "bool \fBisExecution\fP () const override"
.br
.RI "Проверяет, выполняется ли приложение\&. "
.in -1c

Открытые члены унаследованные от \fBTetris::View::IApplication\fP
.in +1c
.ti -1c
.RI "virtual \fB~IApplication\fP ()=default"
.br
.RI "Дефолтный деструктор "
.in -1c
.SH "Подробное описание"
.PP 
Класс, реализующий интерфейс \fBIApplication\fP для графического приложения на базе SFML\&. 
.SH "Конструктор(ы)"
.PP 
.SS "Tetris::View::SFML::SFMLApplication::SFMLApplication (AbstractModelPtr model, unsigned int countWidgets, const std::string & fontPath)"

.PP
Конструктор\&. 
.PP
\fBАргументы\fP
.RS 4
\fImodel\fP Указатель на модель приложения\&. 
.br
\fIcountWidgets\fP Количество виджетов, которые необходимо создать\&. 
.br
\fIfontPath\fP Путь к файлу шрифта\&. 
.RE
.PP

.SH "Методы"
.PP 
.SS "bool Tetris::View::SFML::SFMLApplication::isExecution () const\fR [override]\fP, \fR [virtual]\fP"

.PP
Проверяет, выполняется ли приложение\&. 
.PP
\fBВозвращает\fP
.RS 4
true, если приложение выполняется; false в противном случае\&. 
.RE
.PP

.PP
Замещает \fBTetris::View::IApplication\fP\&.

.SH "Автор"
.PP 
Автоматически создано Doxygen для MultiTetris из исходного текста\&.
